#Workflow name
name: Dev Node.js CI

#Events push & pull request to main branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  #single job running called build
  build:
    
    #using latest ubuntu version as os for runner
    runs-on: ubuntu-latest

    steps:
      #Checks out repo (on github actions marketplace)
    - uses: actions/checkout@v4
      #Sets up NodeJS on runner
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
      #Adds required env variables NODE_ENV=test to GITHUB_ENV
    - name: Set environment variables
      run: echo "NODE_ENV=test" >> $GITHUB_ENV
      #npm ci installs dependencies & npm run build runs custom script build if it exists in package.json      
    - name: Prepare dependencies
      run: |
        npm ci
        npm run build --if-present
      #runs custom test script found in package.json 
    - name: Run all tests
      run: npm test
      #This uploads test results to the repo after the github workflow has ran
    - name: Test and code-coverage results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: test-and-code-coverage-report
        path: test-results.txt
