name: Hello CI

on:
  push:
    branches: [ main ]

jobs:
  hello:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: echo message
      run: echo "Hello, CI!"
    - uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: second step
      run: |
        npm install -g cowsay
        cowsay "Pipeline works!"
  
  notify:
    needs: hello

    runs-on: ubuntu-latest

    steps:
    - name: echo message
      run: echo "Hello from Stu"
